### Configurações Globais
@baseUrl = http://localhost:3000
@contentType = application/json

###

### LISTAR TODAS AS ROUPAS
GET {{baseUrl}}/api/roupas
Accept: {{contentType}}

###

### BUSCAR ROUPA PELO ID 1
GET {{baseUrl}}/api/roupas/1
Accept: {{contentType}}

###

### BUSCAR ROUPA PELO ID 5
GET {{baseUrl}}/api/roupas/5
Accept: {{contentType}}

###

### TESTAR ID INVÁLIDO
GET {{baseUrl}}/api/roupas/ABC
Accept: {{contentType}}

###

### TESTAR ROUPA NÃO EXISTENTE
GET {{baseUrl}}/api/roupas/99
Accept: {{contentType}}

###

### CADASTRAR NOVA ROUPA
POST {{baseUrl}}/api/roupas
Content-Type: {{contentType}}

{
    "nome": "Vestido Floral",
    "tamanho": "M",
    "marca": "Marisa",
    "preco": 70,
    "categoria": "Vestido"
}

###

### ATUALIZAR ROUPA
PUT {{baseUrl}}/api/roupas/2
Content-Type: {{contentType}}

{
    "preco": 150
}

###

### DELETAR ROUPA
DELETE {{baseUrl}}/api/roupas/3
Accept: {{contentType}}

###

### TESTAR ROTA INEXISTENTE
GET {{baseUrl}}/api/teste
Accept: {{contentType}}
